# This file contains all available configuration options
# with their default values.

# options for analysis running
run:
  skip-files:
    - cmd/semver/main.go
    - cmd/semver/version/version.go
  tests: false

linters:
  enable-all: true
  disable:
    - wsl
    - lll
    - funlen
    - godox
