project_name: go-semver
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - 386
  ignore:
  - goos: linux
    goarch: 386
  main: ./cmd/semver/main.go
  binary: semver
  ldflags:
  - -s -w -X github.com/pinterb/go-semver/cmd/semver/version.version={{.Version}}  -X github.com/pinterb/go-semver/cmd/semver/version.commit={{.Commit}} -X github.com/pinterb/go-semver/cmd/semver/version.date={{.Date}}
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
  - goos: windows
    format: zip
brews:
- github:
    owner: pinterb
    name: homebrew-tap
  folder: Formula
  description: A tool to manage semantic versioning of software
  test: |
    system "#{bin}/semver version"
nfpms:
- name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  description: A tool to manage semantic versioning of software
  maintainer: Brad Pinter <brad.pinter@gmail.com>
  license: MIT
  formats:
  - deb
  - rpm
  dependencies:
  - git
