project_name: go-semver
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - 386
  ignore:
  - goos: linux
    goarch: 386
  main: ./cmd/semver/main.go
  binary: semver
  ldflags:
  - -s -w -X github.com/pinterb/go-semver/cmd/semver/version.version={{.Version}}  -X github.com/pinterb/go-semver/cmd/semver/version.commit={{.Commit}} -X github.com/pinterb/go-semver/cmd/semver/version.date={{.Date}}
brews:
- folder: Formula
  github:
    owner: pinterb
    name: homebrew-tap
  description: Get the contributor stats summary from all repos of any given organization
nfpms:
- formats:
    - deb
    - rpm
